[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"
evm_version = "paris"
remappings = [
  "src/=src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
